In [59]:
"""
Minimal character-level Vanilla RNN model. Written by Andrej Karpathy (@karpathy)
BSD License
"""
import numpy as np

# data I/O
#data = open('input.txt', 'r').read() # should be simple plain text file
data = "hello"
chars = list(set(data))
data_size, vocab_size = len(data), len(chars)
print ('data has %d characters, %d unique.' % (data_size, vocab_size))
char_to_ix = { ch:i for i,ch in enumerate(chars) }
ix_to_char = { i:ch for i,ch in enumerate(chars) }

# hyperparameters
#hidden_size = 100 # size of hidden layer of neurons
#seq_length = 25 # number of steps to unroll the RNN for
hidden_size = 3 # size of hidden layer of neurons
seq_length = 4 # number of steps to unroll the RNN for
learning_rate = 1e-1

# model parameters
Wxh = np.random.randn(hidden_size, vocab_size)*0.01 # input to hidden
Whh = np.random.randn(hidden_size, hidden_size)*0.01 # hidden to hidden
Why = np.random.randn(vocab_size, hidden_size)*0.01 # hidden to output
bh = np.zeros((hidden_size, 1)) # hidden bias
by = np.zeros((vocab_size, 1)) # output bias

Whh = np.array([[.1, .5, .1], 
                [.5, .9, .3], 
                [.3, .2, .1]])
Wxh = np.array([[.6, .8, .4, .8],
                [.2, .2, .8, .7],
                [.9, .8, .1, .2]])
Why = np.array([[.9, .8, .3],
                [.2, .3, .4],
                [.6, .9, .1],
                [.5, 0, .3]])

print(char_to_ix)
print('')
print(ix_to_char)
Whh


data has 5 characters, 4 unique.
{'h': 0, 'e': 1, 'l': 2, 'o': 3}

{0: 'h', 1: 'e', 2: 'l', 3: 'o'}


array([[0.1, 0.5, 0.1],
       [0.5, 0.9, 0.3],
       [0.3, 0.2, 0.1]])

In [63]:
def lossFun(inputs, targets, hprev):
  """
  inputs,targets are both list of integers.
  hprev is Hx1 array of initial hidden state
  returns the loss, gradients on model parameters, and last hidden state
  """
  xs, hs, ys, ps = {}, {}, {}, {}
  hs[-1] = np.copy(hprev)
  loss = 0
  # forward pass
  for t in range(len(inputs)):
    xs[t] = np.zeros((vocab_size,1)) # encode in 1-of-k representation
    xs[t][inputs[t]] = 1
    hs[t] = np.tanh(np.dot(Wxh, xs[t]) + np.dot(Whh, hs[t-1]) + bh) # hidden state
    ys[t] = np.dot(Why, hs[t]) + by # unnormalized log probabilities for next chars
    ps[t] = np.exp(ys[t]) / np.sum(np.exp(ys[t])) # probabilities for next chars
    loss += -np.log(ps[t][targets[t],0]) # softmax (cross-entropy loss)
  # backward pass: compute gradients going backwards
  dWxh, dWhh, dWhy = np.zeros_like(Wxh), np.zeros_like(Whh), np.zeros_like(Why)
  dbh, dby = np.zeros_like(bh), np.zeros_like(by)
  dhnext = np.zeros_like(hs[0])
  for t in reversed(range(len(inputs))):
    dy = np.copy(ps[t])
    dy[targets[t]] -= 1 # backprop into y. see http://cs231n.github.io/neural-networks-case-study/#grad if confused here
    dWhy += np.dot(dy, hs[t].T)
    dby += dy
    dh = np.dot(Why.T, dy) + dhnext # backprop into h
    dhraw = (1 - hs[t] * hs[t]) * dh # backprop through tanh nonlinearity
    dbh += dhraw
    dWxh += np.dot(dhraw, xs[t].T)
    dWhh += np.dot(dhraw, hs[t-1].T)
    dhnext = np.dot(Whh.T, dhraw)
  for dparam in [dWxh, dWhh, dWhy, dbh, dby]:
    np.clip(dparam, -5, 5, out=dparam) # clip to mitigate exploding gradients
  return loss, dWxh, dWhh, dWhy, dbh, dby, hs[len(inputs)-1]


def sample(h, seed_ix, n):
  """ 
  sample a sequence of integers from the model 
  h is memory state, seed_ix is seed letter for first time step
  """
  x = np.zeros((vocab_size, 1))
  x[seed_ix] = 1
  ixes = []
  for t in range(n):
    # print(x)
    # print(Wxh)
    # print(h)
    # print(Whh)
    # print(np.dot(Whh, h))
    h = np.tanh(np.dot(Wxh, x) + np.dot(Whh, h) + bh)
    y = np.dot(Why, h) + by
    p = np.exp(y) / np.sum(np.exp(y))
    ix = np.random.choice(range(vocab_size), p=p.ravel())
    x = np.zeros((vocab_size, 1))
    x[ix] = 1
    ixes.append(ix)
  return ixes




In [64]:
n, p = 0, 0
mWxh, mWhh, mWhy = np.zeros_like(Wxh), np.zeros_like(Whh), np.zeros_like(Why)
mbh, mby = np.zeros_like(bh), np.zeros_like(by) # memory variables for Adagrad
smooth_loss = -np.log(1.0/vocab_size)*seq_length # loss at iteration 0
while True:
  # prepare inputs (we're sweeping from left to right in steps seq_length long)
  if p+seq_length+1 >= len(data) or n == 0: 
    hprev = np.zeros((hidden_size,1)) # reset RNN memory
    p = 0 # go from start of data
  inputs = [char_to_ix[ch] for ch in data[p:p+seq_length]]
  targets = [char_to_ix[ch] for ch in data[p+1:p+seq_length+1]]

  # sample from the model now and then
  if n % 100 == 0:
    sample_ix = sample(hprev, inputs[0], 200)
    txt = ''.join(ix_to_char[ix] for ix in sample_ix)
    print ('----\n %s \n----' % (txt, ))

  # forward seq_length characters through the net and fetch gradient
  loss, dWxh, dWhh, dWhy, dbh, dby, hprev = lossFun(inputs, targets, hprev)
  smooth_loss = smooth_loss * 0.999 + loss * 0.001
  if n % 100 == 0: print ('iter %d, loss: %f' % (n, smooth_loss)) # print progress
  
  # perform parameter update with Adagrad
  for param, dparam, mem in zip([Wxh, Whh, Why, bh, by], 
                                [dWxh, dWhh, dWhy, dbh, dby], 
                                [mWxh, mWhh, mWhy, mbh, mby]):
    mem += dparam * dparam
    param += -learning_rate * dparam / np.sqrt(mem + 1e-8) # adagrad update

  p += seq_length # move data pointer
  n += 1 # iteration counter 

ooellloeellooelloooellooeellooellloeelloeelloe 
----
iter 41300, loss: 0.000314
----
 ellooellooeelloeellooelloooellooeellooellloeelloeellooellloeelloeelloeelloeelloeelloeellooeelloeellooellooeellooellloeelloeelloeellooeelooeelloeelloeellooelllooelloooellooeelloeellooellloeelloeelloeel 
----
iter 41400, loss: 0.000313
----
 ellooellloeelloeellooellloeelloeelloeellooelllooellloeelloeelloeelloeellooellloeelloeelloeellooellloeelloeelloeelloeelloeelloeellooeelloeellooellloeelloeelloeellooelloooellloeelloeellooellooeelloeello 
----
iter 41500, loss: 0.000312
----
 elloeellooellloeelloeelloeelloeelloeellooeelloeelloeelloeelloeellooellooeelloeelloeelloeelloeellooeelloeelloeellooellloeelloeelloeelloeellooellooeelloeelloeelloeelloeellooellloeelloeelloeellooellooeel 
----
iter 41600, loss: 0.000311
----
 ellooellloeellooellloeelloeelloeellooellloeellooellooeelloeelloeellooellloeelloeelloeellooellloeelloeelloeellooellloeellooellloeellooelloooellooeelloeelloeelloeelloeelloeelloeellooeelloeellooell

In [ ]:
n, p = 0, 0
mWxh, mWhh, mWhy = np.zeros_like(Wxh), np.zeros_like(Whh), np.zeros_like(Why)
mbh, mby = np.zeros_like(bh), np.zeros_like(by) # memory variables for Adagrad
smooth_loss = -np.log(1.0/vocab_size)*seq_length # loss at iteration 0
#while True:


# prepare inputs (we're sweeping from left to right in steps seq_length long)
if p+seq_length+1 >= len(data) or n == 0: 
hprev = np.zeros((hidden_size,1)) # reset RNN memory
p = 0 # go from start of data
inputs = [char_to_ix[ch] for ch in data[p:p+seq_length]]
targets = [char_to_ix[ch] for ch in data[p+1:p+seq_length+1]]

# sample from the model now and then
if n % 100 == 0:
sample_ix = sample(hprev, inputs[0], 200)
txt = ''.join(ix_to_char[ix] for ix in sample_ix)
print '----\n %s \n----' % (txt, )

# forward seq_length characters through the net and fetch gradient
loss, dWxh, dWhh, dWhy, dbh, dby, hprev = lossFun(inputs, targets, hprev)
smooth_loss = smooth_loss * 0.999 + loss * 0.001
if n % 100 == 0: print 'iter %d, loss: %f' % (n, smooth_loss) # print progress

# perform parameter update with Adagrad
for param, dparam, mem in zip([Wxh, Whh, Why, bh, by], 
                            [dWxh, dWhh, dWhy, dbh, dby], 
                            [mWxh, mWhh, mWhy, mbh, mby]):
mem += dparam * dparam
param += -learning_rate * dparam / np.sqrt(mem + 1e-8) # adagrad update

p += seq_length # move data pointer
n += 1 # iteration counter 



In [18]:
Wxh

array([[0.6, 0.8, 0.4, 0.8],
       [0.2, 0.2, 0.8, 0.7],
       [0.9, 0.8, 0.1, 0.2]])

In [14]:
Ht0 = [[0.2], [0.1], [0.3]]
Ht0
x1 = [[1], [0], [0], [0]]

In [21]:
a1 = np.dot(Wxh, x1 )


In [32]:
h1 = np.tanh(a1)
h1

array([[0.53704957],
       [0.19737532],
       [0.71629787]])

In [40]:
from scipy.special import softmax

# def softmax(x, axis=None):
#     return np.exp(x - logsumexp(x, axis=axis, keepdims=True))

Why = np.array([[.9, .8, .3],
                [.2, .3, .4],
                [.6, .9, .1],
                [.5, 0, .3]])

y1 = np.dot(Why, h1)
y1

array([[0.85613423],
       [0.45314166],
       [0.57149732],
       [0.48341414]])

In [41]:
out = softmax(y1)
out.sum()

1.0000000000000002

In [ ]:
xs[t] = np.zeros((vocab_size,1)) # encode in 1-of-k representation
xs[t][inputs[t]] = 1
hs[t] = np.tanh(np.dot(Wxh, xs[t]) + np.dot(Whh, hs[t-1]) + bh) # hidden state
ys[t] = np.dot(Why, hs[t]) + by # unnormalized log probabilities for next chars
ps[t] = np.exp(ys[t]) / np.sum(np.exp(ys[t])) # probabilities for next chars
loss += -np.log(ps[t][targets[t],0]) # softmax (cross-entropy loss)